# Generated by Django 3.1.7 on 2021-04-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210407_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodel',
            old_name='mobile',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
