# Generated by Django 3.1.7 on 2021-04-08 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210407_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=core.models.IntegerRangeField(default=7056537787, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_no_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
